# Refer https://github.com/zyrouge/pong#configuration for documentation

urls:
    - path: "https://hst.ujol.dev"
      type: "get"
    - path: "https://reddviz.ujol.dev"
      type: "get"
    - path: "https://memeapi.cyclic.app"
      type: "get"
    - path: "https://klik.onrender.com/health"
      type: "get"
    - path: "https://dumb.onrender.com"
      type: "get"
